### ISSUE TITLE
Create Kanban board.

### ISSUE THREAD

**Issue by Omwomo** [Omwomo/space-travelers-hub#25]
## https://github.com/Omwomo/space-travelers-hub/projects/1
- Created a kanban board of two people.
- One of our partner left due to personal issues, so we are just working on the project two of us.
- @Omwomo is doing all tasks related to rockets.
- @George7h is tackling all mission related tasks.

**Comment by prolajumokeoni** [comment]
Hi @Omwomo and @George7h, please update the issue link above with link to your kanban board(Github project)

**Comment by Omwomo** [comment]
Hello @prolajumokeoni , I've implemented your request.

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by prolajumokeoni** [comment]
Hi @Team

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted an issue that does not have correct information of the number of people in your team and the appropriate cards 👍🏿 

- Kindly add a screenshot or approval you got from Student Success that allows you to continue your project without the third partner

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Omwomo** [comment]
Hello @prolajumokeoni , we highlighted the matter regarding third partner in the issue. "One of our partner left due to personal issues, so we are just working on the project two of us." He said he was sick, so he contacted the student success team that he is going to opt out of the program for now.

**Comment by prolajumokeoni** [comment]
> Hello @prolajumokeoni , we highlighted the matter regarding third partner in the issue. "One of our partner left due to personal issues, so we are just working on the project two of us." He said he was sick, so he contacted the student success team that he is going to opt out of the program for now.

Hi, Kindly add a screenshot or approval you got from Student Success that allows you to continue your project without the third partner,  you need to get a go-ahead to work without your partner that is unavailable, I updated the invalidation message above 👍🏿

**Comment by George7h** [comment]
<img width="945" alt="image" src="https://github.com/Omwomo/space-travelers-hub/assets/101390796/423a9eb5-7ebf-4e0f-b621-8906d40a6dcf">

<img width="440" alt="image" src="https://github.com/Omwomo/space-travelers-hub/assets/101390796/78512b9a-a438-4130-a1a4-a3653c6fa7f4">

**Comment by topeogunleye** [comment]
Hi @George7h, @Omwomo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![dwayne-the-rock](https://user-images.githubusercontent.com/52934128/180645370-67438f1f-e27d-4f8b-88d6-1e3474394f0a.gif)

## (Highlights) Good Points: 💪 
**Code Review Summary 🚀**

📌 Your project met the initial requirements effectively by providing the GitHub project link and specifying the number of team members.

📌 You successfully duplicated the project board template, ensuring your board aligns with the required structure.

📌 Great job on managing the cards in the Backlog; having 17 cards demonstrates proper planning.

📌 All cards are assigned to team members, as indicated by the avatars on each card. This showcases excellent task allocation.


**Overall, your project is off to a great start! Keep up the good work and continue collaborating effectively with your team. If you address the suggestions, your project will be even stronger. Happy coding!** 👏👏👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
